// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs8fMEeVBCUU-WLrOyxp9xw4pqtoCm4AA',
    appId: '1:973277722131:web:1d1de70f6cf1ca168f31e6',
    messagingSenderId: '973277722131',
    projectId: 'photohire-4c7a4',
    authDomain: 'photohire-4c7a4.firebaseapp.com',
    storageBucket: 'photohire-4c7a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjs2sWsdM_vLHLW_Eg9bYkrb51BxHbV6c',
    appId: '1:973277722131:android:5c98e208d78463f88f31e6',
    messagingSenderId: '973277722131',
    projectId: 'photohire-4c7a4',
    storageBucket: 'photohire-4c7a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6mDnzoG2g87-l4M-Ff6VjVEqGqPzXFhU',
    appId: '1:973277722131:ios:9b87bcc0475482bf8f31e6',
    messagingSenderId: '973277722131',
    projectId: 'photohire-4c7a4',
    storageBucket: 'photohire-4c7a4.firebasestorage.app',
    iosBundleId: 'com.example.photohire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6mDnzoG2g87-l4M-Ff6VjVEqGqPzXFhU',
    appId: '1:973277722131:ios:9b87bcc0475482bf8f31e6',
    messagingSenderId: '973277722131',
    projectId: 'photohire-4c7a4',
    storageBucket: 'photohire-4c7a4.firebasestorage.app',
    iosBundleId: 'com.example.photohire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs8fMEeVBCUU-WLrOyxp9xw4pqtoCm4AA',
    appId: '1:973277722131:web:4c60f0f1ec26fa8a8f31e6',
    messagingSenderId: '973277722131',
    projectId: 'photohire-4c7a4',
    authDomain: 'photohire-4c7a4.firebaseapp.com',
    storageBucket: 'photohire-4c7a4.firebasestorage.app',
  );
}
